### ISSUE TITLE
TRNSYS Errors

### ISSUE THREAD

**Issue by YuanZhongYan** [DrTol/TRNSYSfromPython#1]
After running TRNSYS by the Python scripts dozens of times TRNSYS an error occurs, as seen in the pictures, and I find it's a soft problem that can only fix it by reinstalling TRNSYS software. Can you help me to solve this problem with a better solution?
![image](https://github.com/DrTol/TRNSYSfromPython/assets/122718167/de11edad-476c-4ccc-8aff-e8a8038cfdfb)
![image](https://github.com/DrTol/TRNSYSfromPython/assets/122718167/9ca85478-cc61-478c-ab1c-0f847d1796f3)
![image](https://github.com/DrTol/TRNSYSfromPython/assets/122718167/064829cf-4d4f-456e-b83d-005d54fc76f6)
![image](https://github.com/DrTol/TRNSYSfromPython/assets/122718167/6c769098-56ce-4e04-96ea-c8a5128a728b)

**Comment by DrTol** [comment]
Did you check if your process address true? It shall be like this: "C:\Trnsys17\Exe\TRNExe.exe"

**Comment by YuanZhongYan** [comment]
Oh my god,  I set the process address as "C:\TRNSYS18\Building\TRNBuild.exe", and the problem has already fixed. Thanks a lot bro.

**Comment by DrTol** [comment]
You are most welcome bro. Enjoy :)
